"""Render .pyi source from collected stub information."""
from __future__ import annotations

import inspect
from typing import Any

from conscribe.stubs.collector import ClassStubInfo


def generate_module_stub(module_name: str, classes: list[ClassStubInfo]) -> str:
    """Generate a ``.pyi`` stub source for all *classes* in one module.

    The output includes a module-level ``__getattr__`` fallback so that
    names not listed in the stub resolve to ``Any`` rather than
    becoming invisible (partial-stub pattern).
    """
    if not classes:
        return ""

    typing_imports: set[str] = {"Any"}  # always needed for __getattr__
    extra_imports: dict[str, set[str]] = {}  # {module: {name, ...}}

    # Collect all imports first ────────────────────────────────────
    for info in classes:
        _collect_class_imports(info, typing_imports, extra_imports)

    # Remove self-module imports (classes defined in this module)
    extra_imports.pop(module_name, None)

    # Build source ────────────────────────────────────────────────
    parts: list[str] = [
        f"# Auto-generated by conscribe. DO NOT EDIT.",
        f"# Stub file for: {module_name}",
        "from __future__ import annotations",
        "",
    ]

    # typing imports
    if typing_imports:
        names = ", ".join(sorted(typing_imports))
        parts.append(f"from typing import {names}")

    # external imports
    for mod in sorted(extra_imports):
        names = ", ".join(sorted(extra_imports[mod]))
        parts.append(f"from {mod} import {names}")

    parts.append("")

    # Module-level __getattr__ (partial stub)
    parts.append("def __getattr__(name: str) -> Any: ...")
    parts.append("")

    # Class stubs
    for info in classes:
        parts.append(_render_class(info))

    return "\n".join(parts) + "\n"


# ── Class rendering ──────────────────────────────────────────────


def _render_class(info: ClassStubInfo) -> str:
    """Render a single class stub."""
    lines: list[str] = []

    # Class declaration
    bases_str = ", ".join(
        b.__name__ for b in info.bases if b is not object
    )
    if bases_str:
        lines.append(f"class {info.class_name}({bases_str}):")
    else:
        lines.append(f"class {info.class_name}:")

    body_lines: list[str] = []

    # Injected wired attributes
    for attr in info.injected_attrs:
        type_name = _type_display_name(attr.resolved_type)
        comment = ""
        if attr.registry_name:
            comment = f"  # wired from: {attr.registry_name}"
        body_lines.append(f"    {attr.name}: {type_name}{comment}")

    if body_lines and (info.init_signature or info.methods):
        body_lines.append("")  # blank line after attrs

    # __init__
    if info.init_signature is not None:
        body_lines.append(f"    def __init__{info.init_signature}: ...")

    # Own methods
    for method in info.methods:
        for dec in method.decorators:
            body_lines.append(f"    {dec}")
        body_lines.append(f"    def {method.name}{method.signature}: ...")

    if not body_lines:
        body_lines.append("    ...")

    lines.extend(body_lines)
    lines.append("")  # trailing blank line
    return "\n".join(lines)


# ── Import collection ────────────────────────────────────────────


def _collect_class_imports(
    info: ClassStubInfo,
    typing_imports: set[str],
    extra_imports: dict[str, set[str]],
) -> None:
    """Populate import sets from a single ClassStubInfo."""
    # Base classes
    for base in info.bases:
        if base is object:
            continue
        _add_type_import(base, extra_imports)

    # Injected attribute types
    for attr in info.injected_attrs:
        if attr.resolved_type is str:
            continue  # builtin
        _add_type_import(attr.resolved_type, extra_imports)

    # Type annotations inside __init__ and method signatures
    _collect_signature_imports(info.cls, typing_imports, extra_imports)


def _collect_signature_imports(
    cls: type,
    typing_imports: set[str],
    extra_imports: dict[str, set[str]],
) -> None:
    """Walk own methods (including __init__) and collect annotation imports."""
    from conscribe.config.codegen import (
        _collect_non_builtin_types,
        _collect_type_imports,
    )

    for name, obj in cls.__dict__.items():
        func: Any = None
        if isinstance(obj, classmethod):
            func = obj.__func__
        elif isinstance(obj, staticmethod):
            func = obj.__func__
        elif isinstance(obj, property):
            func = obj.fget
        elif callable(obj):
            func = obj
        else:
            continue

        if func is None:
            continue

        try:
            sig = inspect.signature(func)
        except (ValueError, TypeError):
            continue

        for param in sig.parameters.values():
            ann = param.annotation
            if ann is not inspect.Parameter.empty:
                _collect_type_imports(ann, typing_imports)
                _collect_non_builtin_types(ann, extra_imports)

        ret = sig.return_annotation
        if ret is not inspect.Parameter.empty:
            _collect_type_imports(ret, typing_imports)
            _collect_non_builtin_types(ret, extra_imports)


# ── Helpers ──────────────────────────────────────────────────────


def _type_display_name(tp: type) -> str:
    """Return the short name used in .pyi annotations."""
    name = getattr(tp, "__name__", None)
    return name if name else repr(tp)


def _add_type_import(tp: type, extra_imports: dict[str, set[str]]) -> None:
    mod = getattr(tp, "__module__", None)
    name = getattr(tp, "__name__", None)
    if mod and name and mod not in ("builtins", "typing"):
        extra_imports.setdefault(mod, set()).add(name)
