"""Render .pyi source from collected stub information."""
from __future__ import annotations

import ast
import functools
import importlib
import inspect
import sys
from typing import Annotated, Any, ForwardRef, get_args, get_origin

from conscribe.stubs.collector import ClassStubInfo


# Names that don't need importing — Python builtins and common literals.
_BUILTIN_NAMES: frozenset[str] = frozenset(
    {
        "None", "True", "False", "Ellipsis",
        "int", "float", "str", "bytes", "bool", "complex",
        "list", "dict", "set", "tuple", "frozenset", "type",
        "object", "bytearray", "memoryview", "range", "slice",
    }
)

# Names that should be imported from typing.
_TYPING_NAMES: frozenset[str] = frozenset(
    {
        "Annotated", "Any", "Callable", "ClassVar", "Final",
        "Generic", "Literal", "Optional", "Protocol", "TypeAlias",
        "TypeVar", "Union", "Awaitable", "AsyncIterable",
        "AsyncIterator", "Coroutine", "AsyncGenerator", "Generator",
        "Iterable", "Iterator", "Mapping", "MutableMapping",
        "Sequence", "MutableSequence", "Set", "MutableSet",
        "Tuple", "List", "Dict", "FrozenSet", "Type",
        "NoReturn", "Never", "Self", "Concatenate", "ParamSpec",
        "TypeGuard", "TypedDict", "NotRequired", "Required",
        "overload", "cast", "NewType", "NamedTuple",
    }
)


def generate_module_stub(
    module_name: str,
    classes: list[ClassStubInfo],
    *,
    partial_class_fallback: bool = False,
) -> str:
    """Generate a ``.pyi`` stub source for all *classes* in one module.

    The output includes a module-level ``__getattr__`` fallback so that
    names not listed in the stub resolve to ``Any`` rather than
    becoming invisible (partial-stub pattern).

    Args:
        module_name: The module the stub describes.
        classes: Stub info collected for that module's classes.
        partial_class_fallback: When ``True``, emit a class-level
            ``__getattr__`` returning ``Incomplete`` in each generated
            class. Defaults to ``False`` so IDEs strictly type-check
            against the listed members.
    """
    if not classes:
        return ""

    typing_imports: set[str] = {"Any"}  # always needed for module __getattr__
    extra_imports: dict[str, set[str]] = {}  # {module: {name, ...}}

    if partial_class_fallback:
        # Incomplete is only available in stub files via _typeshed.
        extra_imports.setdefault("_typeshed", set()).add("Incomplete")

    # Collect all imports first ────────────────────────────────────
    for info in classes:
        _collect_class_imports(info, typing_imports, extra_imports)

    # Remove self-module imports (classes defined in this module)
    extra_imports.pop(module_name, None)

    # Build source ────────────────────────────────────────────────
    parts: list[str] = [
        "# Auto-generated by conscribe. DO NOT EDIT.",
        f"# Stub file for: {module_name}",
        "from __future__ import annotations",
        "",
    ]

    # typing imports
    if typing_imports:
        names = ", ".join(sorted(typing_imports))
        parts.append(f"from typing import {names}")

    # external imports
    for mod in sorted(extra_imports):
        names = ", ".join(sorted(extra_imports[mod]))
        parts.append(f"from {mod} import {names}")

    parts.append("")

    # Module-level __getattr__ (partial stub)
    parts.append("def __getattr__(name: str) -> Any: ...")
    parts.append("")

    # Class stubs
    for info in classes:
        parts.append(_render_class(info, partial_class_fallback))

    return "\n".join(parts) + "\n"


# ── Class rendering ──────────────────────────────────────────────


def _render_class(info: ClassStubInfo, partial_class_fallback: bool) -> str:
    """Render a single class stub."""
    lines: list[str] = []

    # Class declaration
    bases_str = ", ".join(
        b.__name__ for b in info.bases if b is not object
    )
    if bases_str:
        lines.append(f"class {info.class_name}({bases_str}):")
    else:
        lines.append(f"class {info.class_name}:")

    body_lines: list[str] = []

    # Injected wired attributes
    for attr in info.injected_attrs:
        type_name = _type_display_name(attr.resolved_type)
        comment = ""
        if attr.registry_name:
            comment = f"  # wired from: {attr.registry_name}"
        body_lines.append(f"    {attr.name}: {type_name}{comment}")

    has_members = info.init_signature or info.methods or partial_class_fallback
    if body_lines and has_members:
        body_lines.append("")  # blank line after attrs

    # __init__
    if info.init_signature is not None:
        body_lines.append(f"    def __init__{info.init_signature}: ...")

    # Own methods
    for method in info.methods:
        for dec in method.decorators:
            body_lines.append(f"    {dec}")
        body_lines.append(f"    def {method.name}{method.signature}: ...")

    # Optional class-level __getattr__ (partial-class fallback)
    if partial_class_fallback:
        body_lines.append(
            "    def __getattr__(self, name: str) -> Incomplete: ..."
        )

    if not body_lines:
        body_lines.append("    ...")

    lines.extend(body_lines)
    lines.append("")  # trailing blank line
    return "\n".join(lines)


# ── Import collection ────────────────────────────────────────────


def _collect_class_imports(
    info: ClassStubInfo,
    typing_imports: set[str],
    extra_imports: dict[str, set[str]],
) -> None:
    """Populate import sets from a single ClassStubInfo."""
    # Base classes
    for base in info.bases:
        if base is object:
            continue
        _add_type_import(base, extra_imports)

    # Injected attribute types
    for attr in info.injected_attrs:
        if attr.resolved_type is str:
            continue  # builtin
        _add_type_import(attr.resolved_type, extra_imports)

    # Type annotations inside __init__ and method signatures
    _collect_signature_imports(info.cls, typing_imports, extra_imports)


def _collect_signature_imports(
    cls: type,
    typing_imports: set[str],
    extra_imports: dict[str, set[str]],
) -> None:
    """Walk own methods (including __init__) and collect annotation imports.

    Handles both resolved type objects and string-form annotations
    (from ``from __future__ import annotations`` or explicit forward
    references). For string annotations, names are resolved against a
    namespace that merges runtime ``cls.__module__`` globals with names
    imported under ``if TYPE_CHECKING:`` blocks in the source file.
    """
    ns = _build_resolution_namespace(cls)

    for obj in cls.__dict__.values():
        func: Any = None
        if isinstance(obj, classmethod):
            func = obj.__func__
        elif isinstance(obj, staticmethod):
            func = obj.__func__
        elif isinstance(obj, property):
            func = obj.fget
        elif callable(obj):
            func = obj
        else:
            continue

        if func is None:
            continue

        try:
            sig = inspect.signature(func)
        except (ValueError, TypeError):
            continue

        for param in sig.parameters.values():
            _collect_annotation(
                param.annotation, ns, typing_imports, extra_imports
            )

        _collect_annotation(
            sig.return_annotation, ns, typing_imports, extra_imports
        )


def _collect_annotation(
    ann: Any,
    ns: dict[str, Any],
    typing_imports: set[str],
    extra_imports: dict[str, set[str]],
) -> None:
    """Collect imports needed to render a single annotation."""
    if ann is inspect.Parameter.empty:
        return

    # Forward references and PEP 563 string annotations.
    if isinstance(ann, str):
        _collect_from_annotation_string(
            ann, ns, typing_imports, extra_imports
        )
        return
    if isinstance(ann, ForwardRef):
        _collect_from_annotation_string(
            ann.__forward_arg__, ns, typing_imports, extra_imports
        )
        return

    # Resolved type object — reuse the existing helpers from codegen.
    from conscribe.config.codegen import (
        _check_type_module,
        _collect_non_builtin_types,
        _collect_type_imports,
    )

    _collect_type_imports(ann, typing_imports)
    _collect_non_builtin_types(ann, extra_imports)

    # ``_collect_type_imports`` doesn't add ``Annotated`` itself to the
    # typing import set, and never walks metadata args. Stubs render the
    # full annotation text verbatim (via ``str(inspect.signature)``), so
    # both the ``Annotated`` name and the metadata classes need imports.
    if get_origin(ann) is Annotated:
        typing_imports.add("Annotated")
        for meta in get_args(ann)[1:]:
            meta_cls = meta if inspect.isclass(meta) else type(meta)
            _check_type_module(meta_cls, extra_imports)


def _collect_from_annotation_string(
    ann_str: str,
    ns: dict[str, Any],
    typing_imports: set[str],
    extra_imports: dict[str, set[str]],
) -> None:
    """Walk an annotation string with AST and collect imports for names.

    Builtin names are skipped, ``typing`` names go to ``typing_imports``,
    and any other identifier is resolved via *ns* to derive the source
    module for its import. Names that cannot be resolved are skipped
    silently — the stub will still ``compile()`` and the IDE will simply
    fall back to ``Any`` for the unresolved reference.
    """
    if not ann_str or not ann_str.strip():
        return
    try:
        tree = ast.parse(ann_str, mode="eval")
    except SyntaxError:
        return

    seen: set[str] = set()
    for node in ast.walk(tree):
        # Plain identifier — resolves to a class/type.
        if isinstance(node, ast.Name):
            _resolve_name(
                node.id, ns, typing_imports, extra_imports, seen
            )
        # Callable in metadata: e.g. ``Field(...)`` inside Annotated.
        # The ``Name`` walk above already covers ``Field``; nothing extra
        # is needed here, but we keep the branch for clarity / future use.
        elif isinstance(node, ast.Call):
            continue
        # Attribute access like ``typing.Annotated`` — import the root.
        elif isinstance(node, ast.Attribute):
            root = _attribute_root(node)
            if root is not None:
                _resolve_name(
                    root, ns, typing_imports, extra_imports, seen
                )


def _resolve_name(
    name: str,
    ns: dict[str, Any],
    typing_imports: set[str],
    extra_imports: dict[str, set[str]],
    seen: set[str],
) -> None:
    """Try to attribute *name* to typing or a third-party module."""
    if name in seen:
        return
    seen.add(name)

    if name in _BUILTIN_NAMES:
        return
    if name in _TYPING_NAMES:
        typing_imports.add(name)
        return

    obj = ns.get(name)
    if obj is None:
        return  # silently unresolved — IDE will degrade to Any

    module = getattr(obj, "__module__", None)
    obj_name = getattr(obj, "__name__", None)
    if module and obj_name and module not in ("builtins", "typing"):
        # Use the *referenced* name from the source so the stub matches
        # what the user wrote, even if the imported alias differs from
        # the underlying class's ``__name__``.
        extra_imports.setdefault(module, set()).add(name)


def _attribute_root(node: ast.Attribute) -> str | None:
    """Return the leftmost identifier of an attribute chain, or ``None``."""
    cur: ast.AST = node
    while isinstance(cur, ast.Attribute):
        cur = cur.value
    if isinstance(cur, ast.Name):
        return cur.id
    return None


# ── TYPE_CHECKING + module-globals namespace ─────────────────────


@functools.lru_cache(maxsize=None)
def _build_resolution_namespace(cls: type) -> dict[str, Any]:
    """Return a name → object mapping for resolving string annotations.

    Combines runtime ``cls.__module__`` globals with names imported
    under ``if TYPE_CHECKING:`` blocks in the source file. The latter
    are not visible at runtime (since ``TYPE_CHECKING`` is ``False``),
    but stubs need their referents to emit imports.

    Cached per ``__module__``; safe because the underlying source file
    rarely changes during a single conscribe run.
    """
    ns: dict[str, Any] = {}

    module = sys.modules.get(cls.__module__)
    if module is not None:
        ns.update(module.__dict__)

    type_checking_names = _scan_type_checking_imports(cls)
    for name, value in type_checking_names.items():
        ns.setdefault(name, value)

    return ns


def _scan_type_checking_imports(cls: type) -> dict[str, Any]:
    """Parse the source file of *cls* and import names from ``TYPE_CHECKING`` blocks."""
    try:
        source_path = inspect.getsourcefile(cls)
    except TypeError:
        return {}
    if source_path is None:
        return {}

    try:
        with open(source_path, "r", encoding="utf-8") as fh:
            source = fh.read()
    except (OSError, UnicodeDecodeError):
        return {}

    try:
        tree = ast.parse(source)
    except SyntaxError:
        return {}

    result: dict[str, Any] = {}
    for node in tree.body:
        if not isinstance(node, ast.If):
            continue
        if not _is_type_checking_test(node.test):
            continue
        for child in node.body:
            if isinstance(child, ast.ImportFrom):
                _import_from(child, result)
            elif isinstance(child, ast.Import):
                _import_plain(child, result)
    return result


def _is_type_checking_test(test: ast.expr) -> bool:
    """Return True if *test* is ``TYPE_CHECKING`` or ``typing.TYPE_CHECKING``."""
    if isinstance(test, ast.Name) and test.id == "TYPE_CHECKING":
        return True
    if (
        isinstance(test, ast.Attribute)
        and test.attr == "TYPE_CHECKING"
        and isinstance(test.value, ast.Name)
        and test.value.id == "typing"
    ):
        return True
    return False


def _import_from(node: ast.ImportFrom, result: dict[str, Any]) -> None:
    """Run ``from M import N as A`` and stash resolved objects in *result*."""
    if node.module is None or node.level:
        # Skip relative imports — resolving them requires the importing
        # module's package, which gets fragile across edge cases.
        return
    try:
        module = importlib.import_module(node.module)
    except Exception:
        return
    for alias in node.names:
        if alias.name == "*":
            continue
        try:
            obj = getattr(module, alias.name)
        except AttributeError:
            continue
        result[alias.asname or alias.name] = obj


def _import_plain(node: ast.Import, result: dict[str, Any]) -> None:
    """Run ``import M as A`` and stash modules in *result*."""
    for alias in node.names:
        try:
            module = importlib.import_module(alias.name)
        except Exception:
            continue
        # ``import a.b.c`` with no asname binds ``a`` (the top-level pkg).
        if alias.asname:
            result[alias.asname] = module
        else:
            top = alias.name.split(".", 1)[0]
            try:
                top_module = importlib.import_module(top)
            except Exception:
                continue
            result[top] = top_module


# ── Helpers ──────────────────────────────────────────────────────


def _type_display_name(tp: type) -> str:
    """Return the short name used in .pyi annotations."""
    name = getattr(tp, "__name__", None)
    return name if name else repr(tp)


def _add_type_import(tp: type, extra_imports: dict[str, set[str]]) -> None:
    mod = getattr(tp, "__module__", None)
    name = getattr(tp, "__name__", None)
    if mod and name and mod not in ("builtins", "typing"):
        extra_imports.setdefault(mod, set()).add(name)
