"""Render .pyi source from collected stub information."""
from __future__ import annotations

import ast
import functools
import importlib
import inspect
import sys
from dataclasses import dataclass, field
from typing import Annotated, Any, ForwardRef, Optional, get_args, get_origin

from conscribe.stubs.collector import ClassStubInfo


# Names that don't need importing — Python builtins and common literals.
_BUILTIN_NAMES: frozenset[str] = frozenset(
    {
        "None", "True", "False", "Ellipsis",
        "int", "float", "str", "bytes", "bool", "complex",
        "list", "dict", "set", "tuple", "frozenset", "type",
        "object", "bytearray", "memoryview", "range", "slice",
    }
)

# Names that should be imported from typing.
_TYPING_NAMES: frozenset[str] = frozenset(
    {
        "Annotated", "Any", "Callable", "ClassVar", "Final",
        "Generic", "Literal", "Optional", "Protocol", "TypeAlias",
        "TypeVar", "Union", "Awaitable", "AsyncIterable",
        "AsyncIterator", "Coroutine", "AsyncGenerator", "Generator",
        "Iterable", "Iterator", "Mapping", "MutableMapping",
        "Sequence", "MutableSequence", "Set", "MutableSet",
        "Tuple", "List", "Dict", "FrozenSet", "Type",
        "NoReturn", "Never", "Self", "Concatenate", "ParamSpec",
        "TypeGuard", "TypedDict", "NotRequired", "Required",
        "overload", "cast", "NewType", "NamedTuple",
    }
)


# ── Imports data structure ───────────────────────────────────────
#
# ``ExtraImports`` maps a source module name to its imported symbols.
# Each symbol entry is ``orig_name → asname_or_None``: a ``None`` asname
# emits ``from M import N``; a non-None asname emits ``from M import N as A``.
# This shape preserves user-written import aliases like
# ``from pydantic import Field as PydanticField`` instead of mangling them
# into ``from pydantic.fields import PydanticField`` (which doesn't exist).
ExtraImports = dict[str, dict[str, Optional[str]]]


@dataclass(frozen=True)
class _ImportRecord:
    """How a name was imported in the source file."""

    module: str
    orig_name: str  # the actual name in the source module
    asname: Optional[str]  # the local alias, or None if not aliased


@dataclass
class _ResolutionContext:
    """Per-class context for resolving annotation strings to imports."""

    ns: dict[str, Any] = field(default_factory=dict)
    aliases: dict[str, _ImportRecord] = field(default_factory=dict)


def _add_import(
    extra_imports: ExtraImports,
    module: str,
    orig_name: str,
    asname: Optional[str],
) -> None:
    """Record ``from <module> import <orig_name> [as <asname>]``."""
    bucket = extra_imports.setdefault(module, {})
    # Prefer the more-specific (aliased) form when both are recorded.
    existing = bucket.get(orig_name, ...)
    if existing is ... or existing is None:
        bucket[orig_name] = asname


def generate_module_stub(
    module_name: str,
    classes: list[ClassStubInfo],
    *,
    partial_class_fallback: bool = False,
) -> str:
    """Generate a ``.pyi`` stub source for all *classes* in one module.

    The output includes a module-level ``__getattr__`` fallback so that
    names not listed in the stub resolve to ``Any`` rather than
    becoming invisible (partial-stub pattern).

    Args:
        module_name: The module the stub describes.
        classes: Stub info collected for that module's classes.
        partial_class_fallback: When ``True``, emit a class-level
            ``__getattr__`` returning ``Incomplete`` in each generated
            class. Defaults to ``False`` so IDEs strictly type-check
            against the listed members.
    """
    if not classes:
        return ""

    typing_imports: set[str] = {"Any"}  # always needed for module __getattr__
    extra_imports: ExtraImports = {}

    if partial_class_fallback:
        # Incomplete is only available in stub files via _typeshed.
        _add_import(extra_imports, "_typeshed", "Incomplete", None)

    # Collect all imports first ────────────────────────────────────
    for info in classes:
        _collect_class_imports(info, typing_imports, extra_imports)

    # Remove self-module imports (classes defined in this module)
    extra_imports.pop(module_name, None)

    # Build source ────────────────────────────────────────────────
    parts: list[str] = [
        "# Auto-generated by conscribe. DO NOT EDIT.",
        f"# Stub file for: {module_name}",
        "from __future__ import annotations",
        "",
    ]

    # typing imports
    if typing_imports:
        names = ", ".join(sorted(typing_imports))
        parts.append(f"from typing import {names}")

    # external imports
    for mod in sorted(extra_imports):
        parts.append(_render_import_line(mod, extra_imports[mod]))

    parts.append("")

    # Module-level __getattr__ (partial stub)
    parts.append("def __getattr__(name: str) -> Any: ...")
    parts.append("")

    # Class stubs
    for info in classes:
        parts.append(_render_class(info, partial_class_fallback))

    return "\n".join(parts) + "\n"


def _render_import_line(module: str, names: dict[str, Optional[str]]) -> str:
    """Render a single ``from <module> import N1, N2 as A2, ...`` line."""
    pieces: list[str] = []
    for orig_name in sorted(names):
        asname = names[orig_name]
        if asname and asname != orig_name:
            pieces.append(f"{orig_name} as {asname}")
        else:
            pieces.append(orig_name)
    return f"from {module} import {', '.join(pieces)}"


# ── Class rendering ──────────────────────────────────────────────


def _render_class(info: ClassStubInfo, partial_class_fallback: bool) -> str:
    """Render a single class stub."""
    lines: list[str] = []

    # Class declaration
    bases_str = ", ".join(
        b.__name__ for b in info.bases if b is not object
    )
    if bases_str:
        lines.append(f"class {info.class_name}({bases_str}):")
    else:
        lines.append(f"class {info.class_name}:")

    body_lines: list[str] = []

    # Injected wired attributes
    for attr in info.injected_attrs:
        type_name = _type_display_name(attr.resolved_type)
        comment = ""
        if attr.registry_name:
            comment = f"  # wired from: {attr.registry_name}"
        body_lines.append(f"    {attr.name}: {type_name}{comment}")

    # Class-level annotated attributes (dataclass-style fields, etc.)
    if info.class_attrs:
        if body_lines:
            body_lines.append("")
        for ca in info.class_attrs:
            body_lines.append(f"    {ca.name}: {ca.annotation}")

    has_members = info.init_signature or info.methods or partial_class_fallback
    if body_lines and has_members:
        body_lines.append("")  # blank line before init/methods

    # __init__
    if info.init_signature is not None:
        body_lines.append(f"    def __init__{info.init_signature}: ...")

    # Own methods
    for method in info.methods:
        for dec in method.decorators:
            body_lines.append(f"    {dec}")
        body_lines.append(f"    def {method.name}{method.signature}: ...")

    # Optional class-level __getattr__ (partial-class fallback)
    if partial_class_fallback:
        body_lines.append(
            "    def __getattr__(self, name: str) -> Incomplete: ..."
        )

    if not body_lines:
        body_lines.append("    ...")

    lines.extend(body_lines)
    lines.append("")  # trailing blank line
    return "\n".join(lines)


# ── Import collection ────────────────────────────────────────────


def _collect_class_imports(
    info: ClassStubInfo,
    typing_imports: set[str],
    extra_imports: ExtraImports,
) -> None:
    """Populate import sets from a single ClassStubInfo."""
    ctx = _build_resolution_context(info.cls)

    # Base classes
    for base in info.bases:
        if base is object:
            continue
        _add_type_import(base, extra_imports)

    # Injected attribute types
    for attr in info.injected_attrs:
        if attr.resolved_type is str:
            continue  # builtin
        _add_type_import(attr.resolved_type, extra_imports)

    # Class-level annotated attribute annotations
    for ca in info.class_attrs:
        _collect_from_annotation_string(
            ca.annotation, ctx, typing_imports, extra_imports
        )

    # Type annotations inside __init__ and method signatures
    _collect_signature_imports(info.cls, ctx, typing_imports, extra_imports)


def _collect_signature_imports(
    cls: type,
    ctx: _ResolutionContext,
    typing_imports: set[str],
    extra_imports: ExtraImports,
) -> None:
    """Walk own methods (including __init__) and collect annotation imports.

    Handles both resolved type objects and string-form annotations
    (from ``from __future__ import annotations`` or explicit forward
    references). For string annotations, names are resolved against a
    namespace that merges runtime ``cls.__module__`` globals with names
    imported under ``if TYPE_CHECKING:`` blocks in the source file. The
    alias map records the *exact* form each name was imported as, so the
    stub can faithfully reproduce ``from pydantic import Field as
    PydanticField``.
    """
    for obj in cls.__dict__.values():
        func: Any = None
        if isinstance(obj, classmethod):
            func = obj.__func__
        elif isinstance(obj, staticmethod):
            func = obj.__func__
        elif isinstance(obj, property):
            func = obj.fget
        elif callable(obj):
            func = obj
        else:
            continue

        if func is None:
            continue

        try:
            sig = inspect.signature(func)
        except (ValueError, TypeError):
            continue

        for param in sig.parameters.values():
            _collect_annotation(
                param.annotation, ctx, typing_imports, extra_imports
            )

        _collect_annotation(
            sig.return_annotation, ctx, typing_imports, extra_imports
        )


def _collect_annotation(
    ann: Any,
    ctx: _ResolutionContext,
    typing_imports: set[str],
    extra_imports: ExtraImports,
) -> None:
    """Collect imports needed to render a single annotation."""
    if ann is inspect.Parameter.empty:
        return

    # Forward references and PEP 563 string annotations.
    if isinstance(ann, str):
        _collect_from_annotation_string(
            ann, ctx, typing_imports, extra_imports
        )
        return
    if isinstance(ann, ForwardRef):
        _collect_from_annotation_string(
            ann.__forward_arg__, ctx, typing_imports, extra_imports
        )
        return

    # Resolved type object — reuse the existing helpers from codegen.
    from conscribe.config.codegen import (
        _check_type_module,
        _collect_non_builtin_types,
        _collect_type_imports,
    )

    _collect_type_imports(ann, typing_imports)

    # Codegen helpers expect ``dict[str, set[str]]``; adapt by collecting
    # into a temp dict and merging with no asname (these come from the
    # runtime type, not the user's source — no alias to preserve).
    temp: dict[str, set[str]] = {}
    _collect_non_builtin_types(ann, temp)

    # ``_collect_type_imports`` doesn't add ``Annotated`` itself to the
    # typing import set, and never walks metadata args. Stubs render the
    # full annotation text verbatim (via ``str(inspect.signature)``), so
    # both the ``Annotated`` name and the metadata classes need imports.
    if get_origin(ann) is Annotated:
        typing_imports.add("Annotated")
        for meta in get_args(ann)[1:]:
            meta_cls = meta if inspect.isclass(meta) else type(meta)
            _check_type_module(meta_cls, temp)

    for module, names in temp.items():
        for name in names:
            _add_import(extra_imports, module, name, None)


def _collect_from_annotation_string(
    ann_str: str,
    ctx: _ResolutionContext,
    typing_imports: set[str],
    extra_imports: ExtraImports,
) -> None:
    """Walk an annotation string with AST and collect imports for names.

    Builtin names are skipped, ``typing`` names go to ``typing_imports``,
    and any other identifier is resolved via the alias map (preferred) or
    the runtime namespace to derive the source module. Names that cannot
    be resolved are skipped silently — the stub will still ``compile()``
    and the IDE will simply fall back to ``Any`` for the unresolved
    reference.
    """
    if not ann_str or not ann_str.strip():
        return
    try:
        tree = ast.parse(ann_str, mode="eval")
    except SyntaxError:
        return

    seen: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Name):
            _resolve_name(
                node.id, ctx, typing_imports, extra_imports, seen
            )
        elif isinstance(node, ast.Call):
            continue
        elif isinstance(node, ast.Attribute):
            root = _attribute_root(node)
            if root is not None:
                _resolve_name(
                    root, ctx, typing_imports, extra_imports, seen
                )


def _resolve_name(
    name: str,
    ctx: _ResolutionContext,
    typing_imports: set[str],
    extra_imports: ExtraImports,
    seen: set[str],
) -> None:
    """Try to attribute *name* to typing or a third-party module.

    Resolution order:
    1. Builtin / typing — handled inline.
    2. Source-file alias map — preserves the exact ``from M import N as A``
       the user wrote.
    3. Runtime namespace — fallback when the name isn't a top-level import
       (e.g., transitively re-exported, defined in the same file, etc.).
    """
    if name in seen:
        return
    seen.add(name)

    if name in _BUILTIN_NAMES:
        return
    if name in _TYPING_NAMES:
        typing_imports.add(name)
        return

    # Prefer the alias map: it captures both the user's chosen module
    # and the original symbol name.
    record = ctx.aliases.get(name)
    if record is not None:
        if record.module == "typing":
            typing_imports.add(record.orig_name)
        elif record.module not in ("builtins",):
            _add_import(
                extra_imports, record.module, record.orig_name, record.asname
            )
        return

    obj = ctx.ns.get(name)
    if obj is None:
        return  # silently unresolved — IDE will degrade to Any

    module = getattr(obj, "__module__", None)
    obj_name = getattr(obj, "__name__", None)
    if module and obj_name and module not in ("builtins", "typing"):
        # Use the *referenced* name from the source so the stub matches
        # what the user wrote, even if the imported alias differs from
        # the underlying class's ``__name__``.
        _add_import(extra_imports, module, name, None)


def _attribute_root(node: ast.Attribute) -> str | None:
    """Return the leftmost identifier of an attribute chain, or ``None``."""
    cur: ast.AST = node
    while isinstance(cur, ast.Attribute):
        cur = cur.value
    if isinstance(cur, ast.Name):
        return cur.id
    return None


# ── Source-file scanning: namespace + alias map ──────────────────


@functools.lru_cache(maxsize=None)
def _build_resolution_context(cls: type) -> _ResolutionContext:
    """Return a name-resolution context for *cls*'s source file.

    The context combines:
    - Runtime ``cls.__module__`` globals (so locally defined names are
      resolvable to their ``__module__`` / ``__name__``).
    - Names imported under ``if TYPE_CHECKING:`` blocks (invisible at
      runtime since ``TYPE_CHECKING`` is ``False``).
    - An alias map of every top-level ``import``/``from``-import in the
      source file, including aliased forms — used to faithfully emit
      ``from pkg import Name as Alias`` in generated stubs.

    Cached per-class; safe because the source file rarely changes
    during a single conscribe run.
    """
    ctx = _ResolutionContext()

    module = sys.modules.get(cls.__module__)
    if module is not None:
        ctx.ns.update(module.__dict__)

    type_checking_names, alias_map = _scan_source_imports(cls)
    for name, value in type_checking_names.items():
        ctx.ns.setdefault(name, value)
    ctx.aliases = alias_map
    return ctx


# Backwards-compatible shim for callers that may still import the
# previous helper name.
def _build_resolution_namespace(cls: type) -> dict[str, Any]:
    return _build_resolution_context(cls).ns


def _scan_source_imports(
    cls: type,
) -> tuple[dict[str, Any], dict[str, _ImportRecord]]:
    """Parse *cls*'s source file for imports.

    Returns ``(type_checking_names, alias_map)`` where:
    - ``type_checking_names``: name → resolved object, drawn from
      ``if TYPE_CHECKING:`` blocks (these are imported now so we can
      resolve their ``__module__`` for runtime-style lookups).
    - ``alias_map``: name → ImportRecord, covering *all* top-level
      imports in the file (TYPE_CHECKING and non-TYPE_CHECKING). Used
      to emit imports in the exact form the user wrote them.
    """
    try:
        source_path = inspect.getsourcefile(cls)
    except TypeError:
        return {}, {}
    if source_path is None:
        return {}, {}

    try:
        with open(source_path, "r", encoding="utf-8") as fh:
            source = fh.read()
    except (OSError, UnicodeDecodeError):
        return {}, {}

    try:
        tree = ast.parse(source)
    except SyntaxError:
        return {}, {}

    type_checking_names: dict[str, Any] = {}
    alias_map: dict[str, _ImportRecord] = {}

    for node in tree.body:
        if isinstance(node, ast.ImportFrom):
            _record_from(node, alias_map)
        elif isinstance(node, ast.Import):
            _record_plain(node, alias_map)
        elif isinstance(node, ast.If) and _is_type_checking_test(node.test):
            for child in node.body:
                if isinstance(child, ast.ImportFrom):
                    _record_from(child, alias_map)
                    _import_from(child, type_checking_names)
                elif isinstance(child, ast.Import):
                    _record_plain(child, alias_map)
                    _import_plain(child, type_checking_names)

    return type_checking_names, alias_map


def _is_type_checking_test(test: ast.expr) -> bool:
    """Return True if *test* is ``TYPE_CHECKING`` or ``typing.TYPE_CHECKING``."""
    if isinstance(test, ast.Name) and test.id == "TYPE_CHECKING":
        return True
    if (
        isinstance(test, ast.Attribute)
        and test.attr == "TYPE_CHECKING"
        and isinstance(test.value, ast.Name)
        and test.value.id == "typing"
    ):
        return True
    return False


def _record_from(node: ast.ImportFrom, alias_map: dict[str, _ImportRecord]) -> None:
    """Record ``from M import N [as A]`` entries into the alias map."""
    if node.module is None or node.level:
        # Skip relative imports — resolving them requires the importing
        # module's package, which gets fragile across edge cases.
        return
    for alias in node.names:
        if alias.name == "*":
            continue
        local = alias.asname or alias.name
        alias_map.setdefault(
            local,
            _ImportRecord(
                module=node.module,
                orig_name=alias.name,
                asname=alias.asname,
            ),
        )


def _record_plain(node: ast.Import, alias_map: dict[str, _ImportRecord]) -> None:
    """Record ``import M [as A]`` entries.

    For the alias map, we treat ``import M`` as binding the top-level
    package and ``import M as A`` as binding ``A`` to the same. The
    ``orig_name`` for plain imports is the module's last segment
    rendered as a top-level name when no asname is given — but since
    annotations more commonly use these via attribute access (``M.X``),
    the AST collector sees the root binding (``M`` or ``A``), which we
    keep here for completeness even though a stub typically wouldn't
    re-emit a bare ``import M``.
    """
    for alias in node.names:
        local = alias.asname or alias.name.split(".", 1)[0]
        alias_map.setdefault(
            local,
            _ImportRecord(
                module=alias.name,
                orig_name=alias.name,
                asname=alias.asname,
            ),
        )


def _import_from(node: ast.ImportFrom, result: dict[str, Any]) -> None:
    """Run ``from M import N as A`` and stash resolved objects in *result*."""
    if node.module is None or node.level:
        return
    try:
        module = importlib.import_module(node.module)
    except Exception:
        return
    for alias in node.names:
        if alias.name == "*":
            continue
        try:
            obj = getattr(module, alias.name)
        except AttributeError:
            continue
        result[alias.asname or alias.name] = obj


def _import_plain(node: ast.Import, result: dict[str, Any]) -> None:
    """Run ``import M as A`` and stash modules in *result*."""
    for alias in node.names:
        try:
            module = importlib.import_module(alias.name)
        except Exception:
            continue
        if alias.asname:
            result[alias.asname] = module
        else:
            top = alias.name.split(".", 1)[0]
            try:
                top_module = importlib.import_module(top)
            except Exception:
                continue
            result[top] = top_module


# ── Helpers ──────────────────────────────────────────────────────


def _type_display_name(tp: type) -> str:
    """Return the short name used in .pyi annotations."""
    name = getattr(tp, "__name__", None)
    return name if name else repr(tp)


def _add_type_import(tp: type, extra_imports: ExtraImports) -> None:
    mod = getattr(tp, "__module__", None)
    name = getattr(tp, "__name__", None)
    if mod and name and mod not in ("builtins", "typing"):
        _add_import(extra_imports, mod, name, None)
