"""Tests for conscribe.stubs.generator."""
from __future__ import annotations

import pytest
from typing import Protocol, runtime_checkable

from conscribe.registration.registry import LayerRegistry, _REGISTRY_INDEX, _deregister
from conscribe.stubs.collector import ClassStubInfo, InjectedAttr, MethodStub, collect_class_stub_info
from conscribe.stubs.generator import generate_module_stub


# ── Fixtures ─────────────────────────────────────────────────────


@runtime_checkable
class EnvProtocol(Protocol):
    def setup(self) -> None: ...


class Terminal:
    def setup(self) -> None: ...


class BashTerminal(Terminal):
    def setup(self) -> None: ...


class ZshTerminal(Terminal):
    def setup(self) -> None: ...


@pytest.fixture(autouse=True)
def _cleanup():
    yield
    for name in list(_REGISTRY_INDEX.keys()):
        if name.startswith("test_"):
            _deregister(name)


def _make_env_registry() -> LayerRegistry:
    reg = LayerRegistry("test_env", EnvProtocol)
    reg.add("terminal.bash", BashTerminal)
    reg.add("terminal.zsh", ZshTerminal)
    return reg


# ── generate_module_stub ─────────────────────────────────────────


class TestGenerateModuleStub:
    def test_empty_classes(self):
        assert generate_module_stub("mod", []) == ""

    def test_basic_structure(self):
        info = ClassStubInfo(
            cls=type("Foo", (), {}),
            class_name="Foo",
            module="mymod",
            source_file="/tmp/mymod.py",
            bases=(object,),
            init_signature=None,
            injected_attrs=(
                InjectedAttr(name="env", resolved_type=Terminal, registry_name="test_env"),
            ),
            methods=(),
        )
        source = generate_module_stub("mymod", [info])

        assert "# Auto-generated by conscribe" in source
        assert "from __future__ import annotations" in source
        assert "def __getattr__(name: str) -> Any: ..." in source
        assert "class Foo:" in source
        assert "env: Terminal" in source
        assert "# wired from: test_env" in source

    def test_includes_base_class(self):
        class Base:
            pass

        info = ClassStubInfo(
            cls=type("Child", (Base,), {}),
            class_name="Child",
            module="mymod",
            source_file="/tmp/mymod.py",
            bases=(Base,),
            init_signature=None,
            injected_attrs=(
                InjectedAttr(name="x", resolved_type=str, registry_name=None),
            ),
            methods=(),
        )
        source = generate_module_stub("mymod", [info])
        assert "class Child(Base):" in source

    def test_init_rendered(self):
        info = ClassStubInfo(
            cls=type("Foo", (), {}),
            class_name="Foo",
            module="mymod",
            source_file="/tmp/mymod.py",
            bases=(object,),
            init_signature="(self, name: str = 'default') -> None",
            injected_attrs=(
                InjectedAttr(name="env", resolved_type=str, registry_name=None),
            ),
            methods=(),
        )
        source = generate_module_stub("mymod", [info])
        assert "def __init__(self, name: str = 'default') -> None: ..." in source

    def test_methods_rendered(self):
        info = ClassStubInfo(
            cls=type("Foo", (), {}),
            class_name="Foo",
            module="mymod",
            source_file="/tmp/mymod.py",
            bases=(object,),
            init_signature=None,
            injected_attrs=(
                InjectedAttr(name="x", resolved_type=str, registry_name=None),
            ),
            methods=(
                MethodStub(name="step", signature="(self, task: str) -> str", decorators=()),
                MethodStub(name="reset", signature="(self)", decorators=()),
            ),
        )
        source = generate_module_stub("mymod", [info])
        assert "def step(self, task: str) -> str: ..." in source
        assert "def reset(self): ..." in source

    def test_classmethod_decorator(self):
        info = ClassStubInfo(
            cls=type("Foo", (), {}),
            class_name="Foo",
            module="mymod",
            source_file="/tmp/mymod.py",
            bases=(object,),
            init_signature=None,
            injected_attrs=(
                InjectedAttr(name="x", resolved_type=str, registry_name=None),
            ),
            methods=(
                MethodStub(name="create", signature="(cls)", decorators=("@classmethod",)),
            ),
        )
        source = generate_module_stub("mymod", [info])
        assert "@classmethod" in source
        assert "def create(cls): ..." in source

    def test_mode3_literal_uses_str(self):
        info = ClassStubInfo(
            cls=type("Foo", (), {}),
            class_name="Foo",
            module="mymod",
            source_file="/tmp/mymod.py",
            bases=(object,),
            init_signature=None,
            injected_attrs=(
                InjectedAttr(name="browser", resolved_type=str, registry_name=None),
            ),
            methods=(),
        )
        source = generate_module_stub("mymod", [info])
        assert "browser: str" in source

    def test_compilable_output(self):
        """Generated source must be valid Python."""
        _make_env_registry()

        class Agent:
            __wiring__ = {"env": ("test_env", ["terminal.bash", "terminal.zsh"])}

            def __init__(self, name: str = "default"):
                self.name = name

            def step(self, task: str) -> str:
                return task

        info = collect_class_stub_info(Agent)
        assert info is not None
        source = generate_module_stub(info.module, [info])

        # Must compile without errors
        compile(source, "<test>", "exec")

    def test_multiple_classes_same_module(self):
        info1 = ClassStubInfo(
            cls=type("Foo", (), {}),
            class_name="Foo",
            module="mymod",
            source_file="/tmp/mymod.py",
            bases=(object,),
            init_signature=None,
            injected_attrs=(
                InjectedAttr(name="x", resolved_type=str, registry_name=None),
            ),
            methods=(),
        )
        info2 = ClassStubInfo(
            cls=type("Bar", (), {}),
            class_name="Bar",
            module="mymod",
            source_file="/tmp/mymod.py",
            bases=(object,),
            init_signature=None,
            injected_attrs=(
                InjectedAttr(name="y", resolved_type=str, registry_name=None),
            ),
            methods=(),
        )
        source = generate_module_stub("mymod", [info1, info2])
        assert "class Foo:" in source
        assert "class Bar:" in source


# ── Annotation resolution (string + Annotated metadata) ──────────


def _stub_for(cls: type) -> str:
    """Wrap *cls* in a ClassStubInfo and render through generate_module_stub."""
    from conscribe.stubs.collector import _collect_class_attrs

    info = ClassStubInfo(
        cls=cls,
        class_name=cls.__name__,
        module=cls.__module__,
        source_file=cls.__module__,
        bases=tuple(b for b in cls.__bases__ if b is not object),
        init_signature=_init_sig_str(cls),
        injected_attrs=(
            InjectedAttr(name="_dummy", resolved_type=str, registry_name=None),
        ),
        methods=_methods_for(cls),
        class_attrs=_collect_class_attrs(cls, skip_names={"_dummy"}),
    )
    return generate_module_stub(info.module, [info])


def _init_sig_str(cls: type):
    import inspect as _inspect

    if "__init__" not in cls.__dict__:
        return None
    sig = _inspect.signature(cls.__init__)
    text = str(sig)
    if sig.return_annotation is _inspect.Parameter.empty:
        text += " -> None"
    return text


def _methods_for(cls: type) -> tuple[MethodStub, ...]:
    import inspect as _inspect

    out: list[MethodStub] = []
    for name, obj in cls.__dict__.items():
        if name in {"__init__", "__module__", "__qualname__", "__doc__", "__dict__", "__weakref__"}:
            continue
        if not callable(obj):
            continue
        try:
            sig = _inspect.signature(obj)
        except (TypeError, ValueError):
            continue
        out.append(MethodStub(name=name, signature=str(sig), decorators=()))
    return tuple(out)


class TestStringAnnotations:
    def test_annotated_metadata_imports_resolved(self):
        from tests.stubs.fixtures.string_annotated import StringAnnotated

        source = _stub_for(StringAnnotated)

        # Annotated and Literal must be imported from typing
        assert "from typing import" in source
        assert "Annotated" in source
        assert "Literal" in source

        # `Field` is the pydantic callable the user wrote — must be
        # imported from its source module so PyCharm/Pylance can resolve.
        assert "Field" in source
        assert "from pydantic" in source  # accepts pydantic or pydantic.fields

        # The literal Annotated[...] text must remain in __init__.
        assert "Annotated[int, Field" in source

        # Stub must compile.
        compile(source, "<test>", "exec")

    def test_type_checking_imports_resolved(self):
        from tests.stubs.fixtures.type_checking_imports import UsesTypeChecking

        source = _stub_for(UsesTypeChecking)

        # OrderedDict comes from a TYPE_CHECKING block; AST scan must
        # surface it into the import set.
        assert "from collections import" in source
        assert "OrderedDict" in source

        # Stub must compile.
        compile(source, "<test>", "exec")

    def test_unresolvable_name_does_not_crash(self):
        from tests.stubs.fixtures.unresolved_name import HasUnresolved

        # Should not raise.
        source = _stub_for(HasUnresolved)

        # Stub must still compile (the unresolved name is in a string
        # annotation, which Python parses lazily under
        # ``from __future__ import annotations``).
        compile(source, "<test>", "exec")

        # And no spurious import was emitted for the unknown name.
        assert "import NeverDefined" not in source


class TestAliasedImports:
    def test_pydantic_field_alias_preserved(self):
        """``from pydantic import Field as PydanticField`` round-trips faithfully.

        Regression test for v1.1.0 → v1.1.1: previously the stub emitted
        ``from pydantic.fields import PydanticField`` (using the alias as
        the *imported* name and the runtime ``__module__`` instead of the
        user's source module), which doesn't resolve.
        """
        from tests.stubs.fixtures.aliased_import import AliasedDataclass

        source = _stub_for(AliasedDataclass)

        # Faithful aliased import — original name + alias preserved.
        assert "from pydantic import Field as PydanticField" in source

        # Negative: the broken form must not appear.
        assert "from pydantic.fields import PydanticField" not in source

        # Stub must compile.
        compile(source, "<test>", "exec")


class TestClassAttrRendering:
    def test_dataclass_fields_appear_in_class_body(self):
        """Public dataclass fields render as class-level annotations."""
        from tests.stubs.fixtures.aliased_import import AliasedDataclass

        source = _stub_for(AliasedDataclass)

        # All three public fields must appear as class-level attrs.
        assert "max_steps:" in source
        assert "use_vision:" in source
        assert "vision_detail:" in source

        # The Annotated[...] metadata is preserved verbatim.
        assert "Annotated[int, PydanticField" in source

    def test_class_attrs_rendered_before_init(self):
        """Class attrs appear in the body, separated from __init__."""
        from tests.stubs.fixtures.aliased_import import AliasedDataclass

        source = _stub_for(AliasedDataclass)
        # Find the class body region.
        class_idx = source.index("class AliasedDataclass")
        init_idx = source.index("def __init__", class_idx)
        body_before_init = source[class_idx:init_idx]
        assert "max_steps:" in body_before_init
        assert "use_vision:" in body_before_init


class TestPartialClassFallback:
    def test_fallback_off_by_default(self):
        info = ClassStubInfo(
            cls=type("Foo", (), {}),
            class_name="Foo",
            module="mymod",
            source_file="/tmp/mymod.py",
            bases=(object,),
            init_signature=None,
            injected_attrs=(
                InjectedAttr(name="x", resolved_type=str, registry_name=None),
            ),
            methods=(),
        )
        source = generate_module_stub("mymod", [info])

        assert "Incomplete" not in source
        # Module-level __getattr__ stays; no class-level one.
        assert source.count("__getattr__") == 1
        assert "(self, name: str) -> Incomplete" not in source

    def test_fallback_on_emits_class_getattr(self):
        info = ClassStubInfo(
            cls=type("Foo", (), {}),
            class_name="Foo",
            module="mymod",
            source_file="/tmp/mymod.py",
            bases=(object,),
            init_signature=None,
            injected_attrs=(
                InjectedAttr(name="x", resolved_type=str, registry_name=None),
            ),
            methods=(),
        )
        source = generate_module_stub(
            "mymod", [info], partial_class_fallback=True,
        )

        assert "from _typeshed import Incomplete" in source
        assert "def __getattr__(self, name: str) -> Incomplete: ..." in source
        # Module-level + one class-level => two __getattr__ lines.
        assert source.count("__getattr__") == 2

        # Stub must compile.
        compile(source, "<test>", "exec")
