"""Tests for conscribe.stubs.generator."""
from __future__ import annotations

import pytest
from typing import Protocol, runtime_checkable

from conscribe.registration.registry import LayerRegistry, _REGISTRY_INDEX, _deregister
from conscribe.stubs.collector import ClassStubInfo, InjectedAttr, MethodStub, collect_class_stub_info
from conscribe.stubs.generator import generate_module_stub


# ── Fixtures ─────────────────────────────────────────────────────


@runtime_checkable
class EnvProtocol(Protocol):
    def setup(self) -> None: ...


class Terminal:
    def setup(self) -> None: ...


class BashTerminal(Terminal):
    def setup(self) -> None: ...


class ZshTerminal(Terminal):
    def setup(self) -> None: ...


@pytest.fixture(autouse=True)
def _cleanup():
    yield
    for name in list(_REGISTRY_INDEX.keys()):
        if name.startswith("test_"):
            _deregister(name)


def _make_env_registry() -> LayerRegistry:
    reg = LayerRegistry("test_env", EnvProtocol)
    reg.add("terminal.bash", BashTerminal)
    reg.add("terminal.zsh", ZshTerminal)
    return reg


# ── generate_module_stub ─────────────────────────────────────────


class TestGenerateModuleStub:
    def test_empty_classes(self):
        assert generate_module_stub("mod", []) == ""

    def test_basic_structure(self):
        info = ClassStubInfo(
            cls=type("Foo", (), {}),
            class_name="Foo",
            module="mymod",
            source_file="/tmp/mymod.py",
            bases=(object,),
            init_signature=None,
            injected_attrs=(
                InjectedAttr(name="env", resolved_type=Terminal, registry_name="test_env"),
            ),
            methods=(),
        )
        source = generate_module_stub("mymod", [info])

        assert "# Auto-generated by conscribe" in source
        assert "from __future__ import annotations" in source
        assert "def __getattr__(name: str) -> Any: ..." in source
        assert "class Foo:" in source
        assert "env: Terminal" in source
        assert "# wired from: test_env" in source

    def test_includes_base_class(self):
        class Base:
            pass

        info = ClassStubInfo(
            cls=type("Child", (Base,), {}),
            class_name="Child",
            module="mymod",
            source_file="/tmp/mymod.py",
            bases=(Base,),
            init_signature=None,
            injected_attrs=(
                InjectedAttr(name="x", resolved_type=str, registry_name=None),
            ),
            methods=(),
        )
        source = generate_module_stub("mymod", [info])
        assert "class Child(Base):" in source

    def test_init_rendered(self):
        info = ClassStubInfo(
            cls=type("Foo", (), {}),
            class_name="Foo",
            module="mymod",
            source_file="/tmp/mymod.py",
            bases=(object,),
            init_signature="(self, name: str = 'default') -> None",
            injected_attrs=(
                InjectedAttr(name="env", resolved_type=str, registry_name=None),
            ),
            methods=(),
        )
        source = generate_module_stub("mymod", [info])
        assert "def __init__(self, name: str = 'default') -> None: ..." in source

    def test_methods_rendered(self):
        info = ClassStubInfo(
            cls=type("Foo", (), {}),
            class_name="Foo",
            module="mymod",
            source_file="/tmp/mymod.py",
            bases=(object,),
            init_signature=None,
            injected_attrs=(
                InjectedAttr(name="x", resolved_type=str, registry_name=None),
            ),
            methods=(
                MethodStub(name="step", signature="(self, task: str) -> str", decorators=()),
                MethodStub(name="reset", signature="(self)", decorators=()),
            ),
        )
        source = generate_module_stub("mymod", [info])
        assert "def step(self, task: str) -> str: ..." in source
        assert "def reset(self): ..." in source

    def test_classmethod_decorator(self):
        info = ClassStubInfo(
            cls=type("Foo", (), {}),
            class_name="Foo",
            module="mymod",
            source_file="/tmp/mymod.py",
            bases=(object,),
            init_signature=None,
            injected_attrs=(
                InjectedAttr(name="x", resolved_type=str, registry_name=None),
            ),
            methods=(
                MethodStub(name="create", signature="(cls)", decorators=("@classmethod",)),
            ),
        )
        source = generate_module_stub("mymod", [info])
        assert "@classmethod" in source
        assert "def create(cls): ..." in source

    def test_mode3_literal_uses_str(self):
        info = ClassStubInfo(
            cls=type("Foo", (), {}),
            class_name="Foo",
            module="mymod",
            source_file="/tmp/mymod.py",
            bases=(object,),
            init_signature=None,
            injected_attrs=(
                InjectedAttr(name="browser", resolved_type=str, registry_name=None),
            ),
            methods=(),
        )
        source = generate_module_stub("mymod", [info])
        assert "browser: str" in source

    def test_compilable_output(self):
        """Generated source must be valid Python."""
        _make_env_registry()

        class Agent:
            __wiring__ = {"env": ("test_env", ["terminal.bash", "terminal.zsh"])}

            def __init__(self, name: str = "default"):
                self.name = name

            def step(self, task: str) -> str:
                return task

        info = collect_class_stub_info(Agent)
        assert info is not None
        source = generate_module_stub(info.module, [info])

        # Must compile without errors
        compile(source, "<test>", "exec")

    def test_multiple_classes_same_module(self):
        info1 = ClassStubInfo(
            cls=type("Foo", (), {}),
            class_name="Foo",
            module="mymod",
            source_file="/tmp/mymod.py",
            bases=(object,),
            init_signature=None,
            injected_attrs=(
                InjectedAttr(name="x", resolved_type=str, registry_name=None),
            ),
            methods=(),
        )
        info2 = ClassStubInfo(
            cls=type("Bar", (), {}),
            class_name="Bar",
            module="mymod",
            source_file="/tmp/mymod.py",
            bases=(object,),
            init_signature=None,
            injected_attrs=(
                InjectedAttr(name="y", resolved_type=str, registry_name=None),
            ),
            methods=(),
        )
        source = generate_module_stub("mymod", [info1, info2])
        assert "class Foo:" in source
        assert "class Bar:" in source
